### PR TITLE
fix(portal): redirect auth

### LINKED ISSUE #360: [Chore] (Portal) - GitHub login fails - redirect is empty
1. On portal, select GitHub auth (with dev tools open)
2. View URL as `https://victorious-river-03cbdf403.3.azurestaticapps.net/.auth/login/github?post_login_redirect_uri=undefined`
3. Is this an issue with SWA build or AZD deploy? 
4. If I go back to root, I am logged in so not blocking but generally annoying.
image

Har attached (remove .txt extension to use)
[20230925-github-social-login-victorious-river-03cbdf403.3.azurestaticapps.net.har.txt](https://github.com/Azure-Samples/contoso-real-estate/files/12718098/20230925-github-social-login-victorious-river-03cbdf403.3.azurestaticapps.net.har.txt)

### PR DESCRIPTION
**Pull request by diberry**
Used this {StackOverflow](https://stackoverflow.com/questions/56005848/angular-how-to-set-default-values-for-optional-input-properties) to fix #360.

### CODE REVIEW

File: packages/portal/src/app/authentication/authentication.component.ts [hunk 1]
```diff
@@ -27,7 +27,12 @@ export class AuthenticationComponent implements OnInit {
     }
   }
 
-  @Input() redirectURL = "/home";
+  @Input() redirectURL='';
```
Comment (manekinekko) [inline packages/portal/src/app/authentication/authentication.component.ts:30]:
```suggestion
  @Input() redirectURL = "";
```

**Review by manekinekko — APPROVED** [review]
